//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "challenges")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub safe_name: String,
    #[sea_orm(column_type = "Text")]
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachment: Option<String>,
    pub hidden: bool,
    #[sea_orm(column_type = "Text")]
    pub toml_str: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::challenge_set_items::Entity")]
    ChallengeSetItems,
    #[sea_orm(has_many = "super::challenge_solves::Entity")]
    ChallengeSolves,
    #[sea_orm(has_many = "super::challenge_writeup::Entity")]
    ChallengeWriteup,
    #[sea_orm(has_many = "super::event_challenge_solves::Entity")]
    EventChallengeSolves,
    #[sea_orm(has_many = "super::event_challenges::Entity")]
    EventChallenges,
    #[sea_orm(has_many = "super::event_instances::Entity")]
    EventInstances,
    #[sea_orm(has_many = "super::instances::Entity")]
    Instances,
}

impl Related<super::challenge_set_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengeSetItems.def()
    }
}

impl Related<super::challenge_solves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengeSolves.def()
    }
}

impl Related<super::challenge_writeup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengeWriteup.def()
    }
}

impl Related<super::event_challenge_solves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallengeSolves.def()
    }
}

impl Related<super::event_challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallenges.def()
    }
}

impl Related<super::event_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInstances.def()
    }
}

impl Related<super::instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instances.def()
    }
}

impl Related<super::challenge_sets::Entity> for Entity {
    fn to() -> RelationDef {
        super::challenge_set_items::Relation::ChallengeSets.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::challenge_set_items::Relation::Challenges.def().rev())
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_challenges::Relation::Events.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_challenges::Relation::Challenges.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
