//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "challenge_set_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub set_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub challenge_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge_sets::Entity",
        from = "Column::SetId",
        to = "super::challenge_sets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChallengeSets,
    #[sea_orm(
        belongs_to = "super::challenges::Entity",
        from = "Column::ChallengeId",
        to = "super::challenges::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Challenges,
}

impl Related<super::challenge_sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengeSets.def()
    }
}

impl Related<super::challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenges.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
