//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "challenge_sets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::challenge_set_items::Entity")]
    ChallengeSetItems,
}

impl Related<super::challenge_set_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengeSetItems.def()
    }
}

impl Related<super::challenges::Entity> for Entity {
    fn to() -> RelationDef {
        super::challenge_set_items::Relation::Challenges.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::challenge_set_items::Relation::ChallengeSets
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
