//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "event_instances")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub instance_id: Uuid,
    pub challenge_id: Uuid,
    pub user_id: Uuid,
    pub team_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenges::Entity",
        from = "Column::ChallengeId",
        to = "super::challenges::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Challenges,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "Column::TeamId",
        to = "super::event_teams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
    #[sea_orm(
        belongs_to = "super::instances::Entity",
        from = "Column::InstanceId",
        to = "super::instances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Instances,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenges.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instances.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
