//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use super::sea_orm_active_enums::EventType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub r#type: EventType,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub hidden: bool,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(column_type = "Text")]
    pub rules: String,
    pub allow_join: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub flag_prefix: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::challenge_solves::Entity")]
    ChallengeSolves,
    #[sea_orm(has_many = "super::event_announcements::Entity")]
    EventAnnouncements,
    #[sea_orm(has_many = "super::event_challenge_solves::Entity")]
    EventChallengeSolves,
    #[sea_orm(has_many = "super::event_challenges::Entity")]
    EventChallenges,
    #[sea_orm(has_many = "super::event_instances::Entity")]
    EventInstances,
    #[sea_orm(has_many = "super::event_team_members::Entity")]
    EventTeamMembers,
    #[sea_orm(has_many = "super::event_teams::Entity")]
    EventTeams,
    #[sea_orm(has_many = "super::event_users::Entity")]
    EventUsers,
    #[sea_orm(has_many = "super::event_writeup::Entity")]
    EventWriteup,
}

impl Related<super::challenge_solves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengeSolves.def()
    }
}

impl Related<super::event_announcements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAnnouncements.def()
    }
}

impl Related<super::event_challenge_solves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallengeSolves.def()
    }
}

impl Related<super::event_challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallenges.def()
    }
}

impl Related<super::event_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInstances.def()
    }
}

impl Related<super::event_team_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeamMembers.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::event_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventUsers.def()
    }
}

impl Related<super::event_writeup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventWriteup.def()
    }
}

impl Related<super::challenges::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_challenges::Relation::Challenges.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_challenges::Relation::Events.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_users::Relation::Events.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
