//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::EventType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "event_logs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub user_id: Option<Uuid>,
    pub team_id: Option<Uuid>,
    pub r#type: EventType,
    pub level: String,
    pub action: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub details: Json,
    pub created_at: DateTimeWithTimeZone,
    pub ip_address: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "Column::TeamId",
        to = "super::event_teams::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    EventTeams,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
