//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "event_teams")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(column_type = "Double")]
    pub points: f64,
    pub banned: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_challenge_solves::Entity")]
    EventChallengeSolves,
    #[sea_orm(has_many = "super::event_instances::Entity")]
    EventInstances,
    #[sea_orm(has_many = "super::event_team_members::Entity")]
    EventTeamMembers,
    #[sea_orm(has_many = "super::event_writeup::Entity")]
    EventWriteup,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::event_challenge_solves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallengeSolves.def()
    }
}

impl Related<super::event_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInstances.def()
    }
}

impl Related<super::event_team_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeamMembers.def()
    }
}

impl Related<super::event_writeup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventWriteup.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
