//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "gameboxes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub safe_name: String,
    #[sea_orm(column_type = "Text")]
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub hidden: bool,
    #[sea_orm(column_type = "Text")]
    pub toml_str: String,
    #[sea_orm(column_type = "Text")]
    pub username: String,
    #[sea_orm(column_type = "Double")]
    pub break_point: f64,
    #[sea_orm(column_type = "Double")]
    pub fix_point: f64,
    #[sea_orm(column_type = "Double")]
    pub down_point: f64,
    #[sea_orm(column_type = "Double")]
    pub first_bouns: f64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_gameboxes::Entity")]
    EventGameboxes,
    #[sea_orm(has_many = "super::instances::Entity")]
    Instances,
}

impl Related<super::event_gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventGameboxes.def()
    }
}

impl Related<super::instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instances.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_gameboxes::Relation::Events.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_gameboxes::Relation::Gameboxes.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
