//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::InstanceStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "instances")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub status: InstanceStatus,
    #[sea_orm(column_type = "Text")]
    pub r#ref: String,
    #[sea_orm(column_type = "Text")]
    pub flag: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub challenge_id: Option<Uuid>,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub identifier: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub destroy_at: DateTime,
    pub gamebox_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenges::Entity",
        from = "Column::ChallengeId",
        to = "super::challenges::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Challenges,
    #[sea_orm(has_many = "super::event_instances::Entity")]
    EventInstances,
    #[sea_orm(
        belongs_to = "super::gameboxes::Entity",
        from = "Column::GameboxId",
        to = "super::gameboxes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Gameboxes,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenges.def()
    }
}

impl Related<super::event_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInstances.def()
    }
}

impl Related<super::gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gameboxes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
