//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub mod prelude;

pub mod challenge_solves;
pub mod challenges;
pub mod event_challenges;
pub mod event_instances;
pub mod event_team_members;
pub mod event_teams;
pub mod event_users;
pub mod events;
pub mod instances;
pub mod sea_orm_active_enums;
pub mod super_admin;
pub mod users;
