//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod announcements;
pub mod challenge_set_items;
pub mod challenge_sets;
pub mod challenge_solves;
pub mod challenge_writeup;
pub mod challenges;
pub mod discussion_comments;
pub mod discussion_likes;
pub mod discussions;
pub mod event_announcements;
pub mod event_challenge_solves;
pub mod event_challenges;
pub mod event_gameboxes;
pub mod event_instances;
pub mod event_logs;
pub mod event_team_members;
pub mod event_teams;
pub mod event_users;
pub mod event_writeup;
pub mod events;
pub mod gameboxes;
pub mod instances;
pub mod kv_store;
pub mod logs;
pub mod scheduled_tasks;
pub mod sea_orm_active_enums;
pub mod settings;
pub mod super_admin;
pub mod users;
pub mod weapons;
