//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::challenge_set_items::Entity as ChallengeSetItems;
pub use super::challenge_sets::Entity as ChallengeSets;
pub use super::challenge_solves::Entity as ChallengeSolves;
pub use super::challenge_writeup::Entity as ChallengeWriteup;
pub use super::challenges::Entity as Challenges;
pub use super::event_announcements::Entity as EventAnnouncements;
pub use super::event_challenge_solves::Entity as EventChallengeSolves;
pub use super::event_challenges::Entity as EventChallenges;
pub use super::event_gameboxes::Entity as EventGameboxes;
pub use super::event_instances::Entity as EventInstances;
pub use super::event_team_members::Entity as EventTeamMembers;
pub use super::event_teams::Entity as EventTeams;
pub use super::event_users::Entity as EventUsers;
pub use super::event_writeup::Entity as EventWriteup;
pub use super::events::Entity as Events;
pub use super::gameboxes::Entity as Gameboxes;
pub use super::instances::Entity as Instances;
pub use super::scheduled_tasks::Entity as ScheduledTasks;
pub use super::settings::Entity as Settings;
pub use super::super_admin::Entity as SuperAdmin;
pub use super::users::Entity as Users;
pub use super::weapons::Entity as Weapons;
