//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "event_team_member_role"
)]
#[serde(rename_all = "snake_case")]
pub enum EventTeamMemberRole {
    #[sea_orm(string_value = "captain")]
    Captain,
    #[sea_orm(string_value = "member")]
    Member,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_type")]
#[serde(rename_all = "snake_case")]
pub enum EventType {
    #[sea_orm(string_value = "jeopardy_practice")]
    JeopardyPractice,
    #[sea_orm(string_value = "jeopardy_single")]
    JeopardySingle,
    #[sea_orm(string_value = "jeopardy_team")]
    JeopardyTeam,
    #[sea_orm(string_value = "awd_team")]
    AwdTeam,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "instance_status")]
#[serde(rename_all = "snake_case")]
pub enum InstanceStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "setting_value_type")]
#[serde(rename_all = "snake_case")]
pub enum SettingValueType {
    #[sea_orm(string_value = "string")]
    String,
    #[sea_orm(string_value = "integer")]
    Integer,
    #[sea_orm(string_value = "boolean")]
    Boolean,
    #[sea_orm(string_value = "float")]
    Float,
}
